/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as esdcMarketplaceSol from "./ESDC_marketplace.sol";
export type { esdcMarketplaceSol };
import type * as esdcNftSol from "./ESDC_nft.sol";
export type { esdcNftSol };
export type { ESDC_token } from "./ESDC_token";
